# ここのファイルは、環境ごとに使えるのもを指定するファイル。
development:
  adapter: async

test:
  adapter: test

production:
# ローカル環境でJSが使えたなら、その記述を真似してみる。
  adapter: async
  # adapter: redis ←これではheroku上でJavaScriptが読み込まれない。
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: furima_31022_production
